services:
  - type: worker
    name: telegram-profil-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN

        sync: false  # Tu le rempliras dans l'interface Render
